version: '3'

volumes:
  locust:
    driver: local

networks: 
  app:
    driver: bridge  

services:
  locust_master:
    image: locustio/locust
    working_dir: /mnt/locust
    restart: always
    networks: 
      - app
    ports:
      - "8989:8089"
    volumes:
      - ./:/mnt/locust
    command: -f /mnt/locust/locustfile.py --master

  locust_worker:
    image: locustio/locust
    restart: always
    networks: 
      - app
    working_dir: /mnt/locust
    depends_on:
      - locust_master
    volumes:
      - ./:/mnt/locust
    command: -f /mnt/locust/locustfile.py --worker --master-host locust_master
    deploy:
      replicas: 3