apiVersion: apps/v1
kind: Deployment
metadata:
  name: primes-app-php
  labels:
    app: primes
    lang: php
spec:
  replicas: 2
  selector:
    matchLabels:
      app: primes
      component: api-php
  template:
    metadata:
      labels:
        app: primes
        component: api-php
    spec:
      containers:
      - name: web-server-php
        image: ekyidag/primes-app-php:d12adac
        resources:
          requests:
            memory: "256Mi"
            cpu: "125m"
          limits:
            memory: "512Mi"
            cpu: "375m"
        ports:
        - containerPort: 8000
        command:
          - "php"
          - "-S"
          - "0.0.0.0:8000"
---
apiVersion: v1
kind: Service
metadata:
  name: primes-service-php
  labels:
    app: primes
    component: api-php
spec:
  type: NodePort
  selector:
      app: primes
      component: api-php
  ports:
      - port: 8000
        nodePort: 30102
