apiVersion: apps/v1
kind: Deployment
metadata:
  name: primes-app-laravel
  labels:
    app: primes
    lang: laravel
spec:
  replicas: 2
  selector:
    matchLabels:
      app: primes
      component: api-laravel
  template:
    metadata:
      labels:
        app: primes
        component: api-laravel
    spec:
      containers:
      - name: web-server-laravel
        image: ekyidag/primes-app-laravel:dev
        imagePullPolicy: Always
        resources:
          requests:
            memory: "256Mi"
            cpu: "125m"
          limits:
            memory: "512Mi"
            cpu: "375m"
        ports:
        - containerPort: 9000
        command:
          - "php"
          - "artisan"
          - "octane:start"
          - "--host=0.0.0.0"
          - "--port=9000"
---
apiVersion: v1
kind: Service
metadata:
  name: primes-service-laravel
  labels:
    app: primes
    component: api-laravel
spec:
  type: NodePort
  selector:
      app: primes
      component: api-laravel
  ports:
      - port: 9000
        nodePort: 30103
